apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data: 
   db_user_name: {{ .Values.env.username | b64enc | quote }}
   db_user_password: {{ .Values.env.password | b64enc | quote }}